[profile.default]
	src = 'contracts'
	# divert scripts during testing to avoid longer compile times
	# The deploy script requires `via_ir` to handle stack depth
	test = 'contracts/test'
	out = 'dist/artifacts'
	libs = ['lib']
	solc-version = "0.8.18"
	optimizer = true
	link = true
	bytecode_hash = "none"
	verbosity = 3
	gas_reports = ["*"]
	script = 'script/solidity'
	libraries = [
		'./contracts/utils/ZeroCheck.sol:ZeroCheck:0x1d40575A69AcAaAC33739b6DcfaE4D6F9A104BE1',
		'./contracts/utils/AddressableTokenId.sol:AddressableTokenId:0xF0eC379F9f77F966E5793BA94a443b795e6eB8e5',
	]
	fs_permissions = [
    { access = "read", path = "./dist"},
    { access = "write", path = "./out"}
  ]

[profile.test]
	# auto-link libraries during testing
	libraries = []

[profile.optimized]
	via_ir = true
	optimizer_runs = 1000000

[profile.swap]
	libs = ['lib','lib_v7']
	src = 'contracts_swap'
	test = 'contracts_swap/test'
	script = 'script/solidity_v7'
	solc_version = "0.7.6"

[fuzz]
	runs = 1024

[fmt]
	indent = 4
	line_length = 80
	tab_width = 4
	bracket_spacing = true
	func_attrs_with_params_multiline = false
	quote_style = "double"

[doc]
	out = 'docs'
	title = 'Sona Protocol'

[etherscan]
	sepolia = { key = "${ETHERSCAN_KEY}", chain = "sepolia" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
